allowBuilds:
  esbuild: true
  unrs-resolver: true

autoInstallPeers: true

blockExoticSubdeps: true

enablePrePostScripts: false

engineStrict: true

minimumReleaseAge: 2880 # 2 days

overrides:
  nanoid@<3.3.18: ^3.3.18

update:
  githubActions: true
