allowBuilds:
  esbuild: true
  unrs-resolver: true

autoInstallPeers: true

blockExoticSubdeps: true

enablePrePostScripts: true

engineStrict: true

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - validate-package-exports@1.5.0

minimumReleaseAgeExcludePrune: true

overrides:
  nanoid@<3.3.18: ^3.3.18

update:
  githubActions: true
