name: Node.js CI

on: [push]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-24.04
    steps:
      - name: Print Runner Specs
        run: |
          lscpu
          cat /proc/meminfo

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Linting last commit message
        if: github.event_name == 'push'
        run: pnpm exec commitlint --last --verbose

      - name: Linting
        run: pnpm lint

      - name: Type checking
        run: pnpm typecheck

      - name: Testing
        run: pnpm coverage

      - name: Building
        run: pnpm build
